pub(crate) mod button;
pub(crate) mod cell;
pub(crate) mod combo;
pub(crate) mod control;
pub(crate) mod edit;
pub(crate) mod imageview;
pub(crate) mod label;
pub(crate) mod layout;
pub(crate) mod listbox;
pub(crate) mod menu;
pub(crate) mod menuitem;
pub(crate) mod panel;
pub(crate) mod popup;
pub(crate) mod progress;
pub(crate) mod slider;
pub(crate) mod splitview;
pub(crate) mod tableview;
pub(crate) mod textview;
pub(crate) mod updown;
pub(crate) mod view;
pub(crate) mod webview;
pub(crate) mod window;

/// Common dialogs are default windows provided by the operating system to perform daily tasks such
/// as: Open files, select colors, fonts, etc.
pub mod dialog;
/// Events are messages that are generated by the user interface and that can be handled by the
pub mod event;

pub use {
    button::*, cell::Cell, combo::Combo, control::ControlTrait, edit::Edit, imageview::ImageView,
    label::Label, layout::*, listbox::ListBox, menu::Menu, menuitem::MenuItem, panel::Panel,
    popup::PopUp, progress::Progress, slider::Slider, splitview::SplitView, tableview::TableView,
    textview::TextView, updown::UpDown, view::View, webview::WebView, window::Window,
};
