mod button;
mod combo;
mod control;
mod edit;
mod imageview;
mod label;
mod layout;
mod line;
mod listbox;
mod menu;
mod menuitem;
mod object;
mod panel;
mod popup;
mod progress;
mod slider;
mod splitview;
mod tableview;
mod textview;
mod updown;
mod view;
mod webview;
mod window;

/// Events are messages that are generated by the user interface and that can be handled by the
pub mod event;

use crate::{
    draw_2d::{Image, Point2D},
    types::GuiTab,
};
pub use {
    button::*, combo::*, control::*, edit::*, imageview::*, label::*, layout::*, line::*, listbox::*, menu::*,
    menuitem::*, object::*, panel::*, popup::*, progress::*, slider::*, splitview::*, tableview::*, textview::*,
    updown::*, view::*, webview::*, window::*,
};

/// Get image from resource
pub fn gui_image(rid: &str) -> &'static Image {
    let rid = std::ffi::CString::new(rid).unwrap();
    let image = Box::leak(Box::new(unsafe { nappgui_sys::gui_image(rid.as_ptr()) }));
    unsafe { std::mem::transmute(image) }
}

/// Get a text string through its resource identifier.
pub fn gui_text(rid: &str) -> String {
    let rid = std::ffi::CString::new(rid).unwrap();
    let text = unsafe { nappgui_sys::gui_text(rid.as_ptr()) };
    let text = unsafe { std::ffi::CStr::from_ptr(text) };
    text.to_string_lossy().to_string()
}

/// Get the contents of a file through its resource identifier.
pub fn gui_file(rid: &str) -> (&[u8], usize) {
    let mut size = 0u32;
    let rid = std::ffi::CString::new(rid).unwrap();
    let file = unsafe { nappgui_sys::gui_file(rid.as_ptr(), &mut size) };
    (
        unsafe { std::slice::from_raw_parts(file, size as usize) },
        size as usize,
    )
}

/// Nappgui resource handler.
pub type NappguiResourceHandler = unsafe extern "C" fn(locale: *const std::ffi::c_char) -> *mut nappgui_sys::ResPack;

/// Register a resource package.
pub fn gui_respack(handler: NappguiResourceHandler) {
    unsafe {
        nappgui_sys::gui_respack(Some(handler));
    }
}

/// Set the language of the registered resources with gui_respack.
pub fn gui_language(language: &str) {
    let language = std::ffi::CString::new(language).unwrap();
    unsafe {
        nappgui_sys::gui_language(language.as_ptr());
    }
}

/// Returns the position of the mouse cursor.
pub fn gui_mouse_postion() -> Point2D {
    let pos = unsafe { nappgui_sys::gui_mouse_pos() };
    Point2D {
        x: pos.x as f32,
        y: pos.y as f32,
    }
}

/// Information about changing the keyboard focus.
pub struct FocusInfo {
    /// Action that has motivated the change of keyboard focus.
    pub action: GuiTab,
    pub(crate) next: *mut nappgui_sys::GuiControl,
}

impl FocusInfo {
    /// Control that has received the focus. TODO!
    pub fn next(&self) -> Option<Control> {
        if self.next.is_null() {
            None
        } else {
            Some(Control::from_raw(self.next))
        }
    }
}
